### ISSUE TITLE
Independent Support is assumed to be in increasing order

### ISSUE THREAD

**Issue by kuldeepmeel** [RafaelTupynamba/quicksampler#6]
Please do not make such assumptions. This makes the system highly unusable.

**Comment by RafaelTupynamba** [comment]
Hi, I don't think I ever made this assumption in the code. The benchmarks from UniGen2 themselves don't have this property.
I use the independent support as a list in the order it's given in the .cnf file (and with the latest commit I also avoid duplicates).

Only if there are no "c ind" lines in the .cnf file indicating the independent support is that I will put all variables that appear in the formula in the independent support, as of the latest commit. In this case, I put them in numerical order, because I don't know any other better ordering.

**Comment by kuldeepmeel** [comment]
You are right. (I had something messed up in my code that led me to believe that solutions printed were in increasing order). 
Btw, why not print solutions in DIMACS format? Or does the new patch takes care of DIMACS format printing?

**Comment by RafaelTupynamba** [comment]
So the output of running `z3 sat.quicksampler_check=true formula.cnf` is a file `formula.cnf.samples.valid` which has only the unique valid solutions in DIMACS format This change is included in the new patch.

For the output of `./quicksampler formula.cnf`, which is the file `formula.cnf.samples`, I prefered to keep it in a more compact format to reduce the usage of disk space and I/O overhead for long running experiments.
